sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm install -g bower
  - npm install -g gulp
  - bower install
script:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
services:
  - mongodb
env:
  - appName=Mean app
  - appSecret=test
  - supportEmail=support@meanapp.io
